### ISSUE TITLE
无法运行,卡死

### ISSUE THREAD

**Issue by hktalent** [2424004764/old_photos_reappear_brilliance#6]
无法运行
docker import face_fix.tar hktalent/face_fix:1.0
docker run --rm -it -v $PWD:/app --name face_fix hktalent/face_fix:1.0 /bin/bash
然后卡死在run上

**Comment by 2424004764** [comment]
不好意思啊，这个很久没有维护了，现在官方都出了docker镜像了，麻烦你用官方的镜像吧～



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月21日(周二) 晚上11:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [2424004764/old_photos_reappear_brilliance] 无法运行,卡死 (Issue #6)




 
无法运行
 docker import face_fix.tar hktalent/face_fix:1.0
 docker run --rm -it -v $PWD:/app --name face_fix hktalent/face_fix:1.0 /bin/bash
 然后卡死在run上

**Comment by hktalent** [comment]
> 不好意思啊，这个很久没有维护了，现在官方都出了docker镜像了，麻烦你用官方的镜像吧～
> […](#)

谢谢,官方的镜像是哪个啊?能告知吗,非常感谢
