### ISSUE TITLE
请问，可以在15寸MacBook Pro上跑起来吗

### ISSUE THREAD

**Issue by zollero** [2424004764/old_photos_reappear_brilliance#7]
不知道这个镜像适不适合MacBook Pro？

**Comment by 2424004764** [comment]
这个有官方docker镜像了，我试过有时候生成不了，图都不给你返回



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月24日(周六) 晚上8:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [2424004764/old_photos_reappear_brilliance] 请问，可以在15寸MacBook Pro上跑起来吗 (Issue #7)




 
不知道这个镜像适不适合MacBook Pro？
